defaults: &defaults
  uri: <%= uri = URI.parse(ENV['REDISCLOUD_URL'] || "redis://localhost:6379") %>
  host: <%= uri.host %>
  port: <%= uri.port %>
  db: 0
  cache_db: 1

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults